[package]
name = "sealing"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-circle = {workspace = true}
p3-matrix = {workspace = true}

itertools = {workspace = true}

primitives = {path = "../primitives"}