[package]
name = "zeropool-sharded-storage-common"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-mersenne-31 = { git = "https://github.com/Plonky3/Plonky3" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3" }
p3-field = { git = "https://github.com/Plonky3/Plonky3" }
serde = "1.0.207"
